### ISSUE TITLE
Error on live app

### ISSUE THREAD

**Issue by robmarkcole** [asehmi/st-media-server#1]
```
requests.exceptions.ConnectionError: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).
```

**Comment by asehmi** [comment]
Yep, I need to remove that share link as I can't figure out how to run a FastAPI server in Streamlit Cloud. That's what's causing the error. Try cloning and running it locally instead. Cheers.

**Comment by robmarkcole** [comment]
You might be able to do it on github codespace

**Comment by asehmi** [comment]
Nice idea... never used that, but have battled all morning with Streamlit Cloud with no luck so probably time to learn. Thanks.

**Comment by asehmi** [comment]
I've given up on getting FastAPI running in Streamlit Cloud. See [st-media-service](https://github.com/asehmi/st-media-service) instead for a non-FastAPI version of this app which does deploy to Streamlit Cloud.
